<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ad;
use App\Models\User;

class AdSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        // Nájdem prvého používateľa (alebo vytvorím testovacieho)
        $user = User::first();
        
        if (!$user) {
            $user = User::create([
                'name' => 'Test User',
                'email' => 'test@example.com',
                'password' => bcrypt('password'),
                'email_verified_at' => now(),
            ]);
        }

        // Vytvorím testovací inzerát 1 - aktívny s predplatným
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Sophia Dreams',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 25,
            'city' => 'bratislava',
            'street' => 'Staré Mesto',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'velmi-skusena',
            'phone' => '+421 900 123 456',
            'contact_methods' => ['telefon', 'sms', 'whatsapp'],
            'hours' => [
                'monday' => ['status' => 'available', 'from' => '09:00', 'to' => '22:00'],
                'tuesday' => ['status' => 'available', 'from' => '09:00', 'to' => '22:00'],
                'wednesday' => ['status' => 'available', 'from' => '09:00', 'to' => '22:00'],
                'thursday' => ['status' => 'available', 'from' => '09:00', 'to' => '22:00'],
                'friday' => ['status' => 'available', 'from' => '09:00', 'to' => '24:00'],
                'saturday' => ['status' => 'available', 'from' => '10:00', 'to' => '24:00'],
                'sunday' => ['status' => 'busy', 'from' => '12:00', 'to' => '20:00']
            ],
            'practices' => ['klasicky-sex', 'oralne', 'masaz', 'escort'],
            'description' => 'Ponúkam profesionálne služby v luxusnom prostredí. Som skúsená a diskrétna. Kontaktujte ma pre viac informácií.',
            'height' => 170,
            'weight' => 55,
            'breast_size' => '75C',
            'eye_color' => 'modre',
            'hair_color' => 'blond',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(25),
            'featured' => true,
            'top_ad' => true,
            'phone_verified' => true,
            'views' => 1247,
            'clicks' => 89,
        ]);

        // Vytvorím testovací inzerát 2 - aktívny bez predplatného
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Alex Escort',
            'ad_type' => 'muz',
            'nationality' => 'ceska',
            'age' => 30,
            'city' => 'kosice',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'stredne-skusena',
            'phone' => '+421 905 987 654',
            'contact_methods' => ['telefon', 'sms'],
            'practices' => ['escort', 'masaz'],
            'description' => 'Diskrétne služby pre náročných klientov. Flexibilné hodiny, možnosť výjazdu.',
            'height' => 180,
            'weight' => 75,
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => true,
            'views' => 856,
            'clicks' => 34,
        ]);

        // Vytvorím testovací inzerát 3 - koncept
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Young Couple',
            'ad_type' => 'par',
            'nationality' => 'slovenska',
            'age' => 28,
            'city' => 'zilina',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'viac-dievcat',
            'experience' => 'neskusena-zaciatocnicka',
            'phone' => '+421 910 555 777',
            'description' => 'Mladý pár hľadá nové zážitky. Sme začiatočníci, ale veľmi otvorení.',
            'status' => 'draft',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => false,
            'views' => 0,
            'clicks' => 0,
        ]);

        // Vytvorím testovací inzerát 4 - vypršané predplatné
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Luna Star',
            'ad_type' => 'trans',
            'nationality' => 'madarská',
            'age' => 26,
            'city' => 'nitra',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 915 444 888',
            'contact_methods' => ['telefon', 'whatsapp'],
            'practices' => ['escort', 'tantra', 'masaz'],
            'description' => 'Exkluzívne služby pre VIP klientov. Diskrétnosť garantovaná.',
            'height' => 175,
            'weight' => 60,
            'breast_size' => '80B',
            'status' => 'active',
            'subscription_status' => 'expired',
            'subscription_expires_at' => now()->subDays(5),
            'featured' => false,
            'phone_verified' => true,
            'views' => 432,
            'clicks' => 28,
        ]);

        // Vytvorím testovací inzerát 5 - klub
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'VIP Club',
            'ad_type' => 'klub',
            'nationality' => 'slovenska',
            'age' => 35,
            'city' => 'bratislava',
            'street' => 'Petržalka',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'viac-dievcat',
            'experience' => 'profesionalka',
            'phone' => '+421 902 111 333',
            'contact_methods' => ['telefon', 'sms', 'whatsapp', 'email'],
            'hours' => [
                'monday' => ['status' => 'available', 'from' => '20:00', 'to' => '06:00'],
                'tuesday' => ['status' => 'available', 'from' => '20:00', 'to' => '06:00'],
                'wednesday' => ['status' => 'available', 'from' => '20:00', 'to' => '06:00'],
                'thursday' => ['status' => 'available', 'from' => '20:00', 'to' => '06:00'],
                'friday' => ['status' => 'available', 'from' => '20:00', 'to' => '08:00'],
                'saturday' => ['status' => 'available', 'from' => '20:00', 'to' => '08:00'],
                'sunday' => ['status' => 'not_working', 'from' => '', 'to' => '']
            ],
            'practices' => ['privat', 'escort', 'masaz', 'tantra', 'skupinove'],
            'description' => 'Exkluzívny klub s najkrajšími dievčatami v meste. Luxusné prostredie, diskrétnosť, profesionalita.',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(15),
            'featured' => true,
            'top_ad' => false,
            'phone_verified' => true,
            'views' => 2156,
            'clicks' => 187,
        ]);

        // Vytvorím testovací inzerát 6 - tantra masáž
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Tantra Goddess',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 32,
            'city' => 'bratislava',
            'street' => 'Ružinov',
            'offer_type' => 'masaz',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 907 888 999',
            'contact_methods' => ['telefon', 'whatsapp'],
            'hours' => [
                'monday' => ['status' => 'available', 'from' => '10:00', 'to' => '20:00'],
                'tuesday' => ['status' => 'available', 'from' => '10:00', 'to' => '20:00'],
                'wednesday' => ['status' => 'available', 'from' => '10:00', 'to' => '20:00'],
                'thursday' => ['status' => 'available', 'from' => '10:00', 'to' => '20:00'],
                'friday' => ['status' => 'available', 'from' => '10:00', 'to' => '22:00'],
                'saturday' => ['status' => 'available', 'from' => '12:00', 'to' => '22:00'],
                'sunday' => ['status' => 'not_working', 'from' => '', 'to' => '']
            ],
            'practices' => ['tantra', 'masaz', 'relaxacne-masaze'],
            'description' => 'Autentická tantra masáž v pokojnom prostredí. Profesionálny prístup, diskrétnosť a relaxácia na najvyššej úrovni.',
            'height' => 165,
            'weight' => 58,
            'breast_size' => '75B',
            'eye_color' => 'hnede',
            'hair_color' => 'cierne',
            'tattoos' => 'ano',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(20),
            'featured' => false,
            'phone_verified' => true,
            'views' => 892,
            'clicks' => 67,
        ]);

        // Inzerát 7 - Mladá žena v Prešove
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Sweet Angel',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 22,
            'city' => 'presov',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'neskusena-zaciatocnicka',
            'phone' => '+421 908 777 555',
            'contact_methods' => ['telefon', 'sms'],
            'practices' => ['klasicky-sex', 'oralne'],
            'description' => 'Mladá študentka hľadá milých pánov. Som nová v tomto biznise ale veľmi chcem sa učiť.',
            'height' => 168,
            'weight' => 52,
            'breast_size' => '70B',
            'eye_color' => 'zelene',
            'hair_color' => 'cerven',
            'tattoos' => 'nie',
            'piercing' => 'ano',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(12),
            'featured' => false,
            'phone_verified' => true,
            'views' => 234,
            'clicks' => 18,
        ]);

        // Inzerát 8 - Muž v Banskej Bystrici
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Strong Man',
            'ad_type' => 'muz',
            'nationality' => 'slovenska',
            'age' => 28,
            'city' => 'banska-bystrica',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'stredne-skusena',
            'phone' => '+421 904 666 333',
            'contact_methods' => ['telefon', 'whatsapp'],
            'practices' => ['escort', 'masaz', 'tantra'],
            'description' => 'Ponúkam diskrétne služby pre dámy. Som športovec, čistý a galantný.',
            'height' => 185,
            'weight' => 80,
            'eye_color' => 'modre',
            'hair_color' => 'hnede',
            'tattoos' => 'ano',
            'piercing' => 'nie',
            'orientation' => 'heterosexualny',
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => true,
            'views' => 445,
            'clicks' => 23,
        ]);

        // Inzerát 9 - Pár v Trnave
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Hot Couple BB',
            'ad_type' => 'par',
            'nationality' => 'slovenska',
            'age' => 29,
            'city' => 'trnava',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'viac-dievcat',
            'experience' => 'velmi-skusena',
            'phone' => '+421 911 888 222',
            'contact_methods' => ['telefon', 'sms', 'whatsapp'],
            'practices' => ['skupinove', 'swinging', 'escort'],
            'description' => 'Mladý atraktívny pár ponúka nezabudnuteľné zážitky. Máme vlastný byt, čisté prostredie.',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(8),
            'featured' => false,
            'phone_verified' => true,
            'views' => 892,
            'clicks' => 67,
        ]);

        // Inzerát 10 - Trans v Martine
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Bella Trans',
            'ad_type' => 'trans',
            'nationality' => 'brazilska',
            'age' => 24,
            'city' => 'martin',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'stredne-skusena',
            'phone' => '+421 903 555 111',
            'contact_methods' => ['telefon', 'whatsapp'],
            'practices' => ['escort', 'tantra', 'masaz'],
            'description' => 'Exotická krása z Brazílie. Ponúkam zmyselné chvíle plné vášne a diskrétnosti.',
            'height' => 172,
            'weight' => 58,
            'breast_size' => '85C',
            'eye_color' => 'hnede',
            'hair_color' => 'cierne',
            'tattoos' => 'ano',
            'piercing' => 'ano',
            'orientation' => 'bisexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(18),
            'featured' => true,
            'phone_verified' => true,
            'views' => 1123,
            'clicks' => 98,
        ]);

        // Inzerát 11 - Masérka v Trenčíne
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Relaxing Hands',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 38,
            'city' => 'trencin',
            'offer_type' => 'masaz',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 912 444 777',
            'contact_methods' => ['telefon', 'sms'],
            'hours' => [
                'monday' => ['status' => 'available', 'from' => '08:00', 'to' => '18:00'],
                'tuesday' => ['status' => 'available', 'from' => '08:00', 'to' => '18:00'],
                'wednesday' => ['status' => 'available', 'from' => '08:00', 'to' => '18:00'],
                'thursday' => ['status' => 'available', 'from' => '08:00', 'to' => '18:00'],
                'friday' => ['status' => 'available', 'from' => '08:00', 'to' => '20:00'],
                'saturday' => ['status' => 'available', 'from' => '10:00', 'to' => '16:00'],
                'sunday' => ['status' => 'not_working', 'from' => '', 'to' => '']
            ],
            'practices' => ['masaz', 'relaxacna-masaz', 'sportova-masaz'],
            'description' => 'Profesionálne masáže s dlhoročnými zkúsenosťami. Vlastný salón, čisté prostredie.',
            'height' => 165,
            'weight' => 60,
            'breast_size' => '80C',
            'eye_color' => 'modre',
            'hair_color' => 'blond',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => true,
            'views' => 567,
            'clicks' => 34,
        ]);

        // Inzerát 12 - VIP Escort Bratislava
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Elite Victoria',
            'ad_type' => 'zena',
            'nationality' => 'ruska',
            'age' => 27,
            'city' => 'bratislava',
            'street' => 'Staré Mesto',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 901 999 888',
            'contact_methods' => ['telefon', 'whatsapp', 'email'],
            'practices' => ['escort', 'vip-service', 'biznis-stretnutia'],
            'description' => 'VIP escort služby pre náročných gentlemanov. Vzdelanie, elegangia, diskrétnosť.',
            'height' => 175,
            'weight' => 56,
            'breast_size' => '85D',
            'eye_color' => 'modre',
            'hair_color' => 'blond',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(30),
            'featured' => true,
            'top_ad' => true,
            'phone_verified' => true,
            'views' => 3456,
            'clicks' => 234,
        ]);

        // Inzerát 13 - Mladý muž v Poprade
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Mountain Boy',
            'ad_type' => 'muz',
            'nationality' => 'slovenska',
            'age' => 25,
            'city' => 'poprad',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'neskusena-zaciatocnicka',
            'phone' => '+421 905 333 666',
            'contact_methods' => ['telefon', 'sms'],
            'practices' => ['klasicky-sex', 'oralne'],
            'description' => 'Mladý športovec z Vysokých Tatier. Som nový, ale veľmi motivovaný.',
            'height' => 178,
            'weight' => 72,
            'eye_color' => 'hnede',
            'hair_color' => 'hnede',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualny',
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => false,
            'views' => 156,
            'clicks' => 8,
        ]);

        // Inzerát 14 - Zrelá žena v Košiciach
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Mature Lady',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 45,
            'city' => 'kosice',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 906 111 222',
            'contact_methods' => ['telefon', 'sms', 'whatsapp'],
            'practices' => ['klasicky-sex', 'oralne', 'masaz', 'tantra'],
            'description' => 'Zrelá žena s bohatými skúsenosťami. Viem čo chcú muži a ako im to dať.',
            'height' => 170,
            'weight' => 65,
            'breast_size' => '90D',
            'eye_color' => 'hnede',
            'hair_color' => 'hnede',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(22),
            'featured' => false,
            'phone_verified' => true,
            'views' => 789,
            'clicks' => 56,
        ]);

        // Inzerát 15 - Klub v Žiline
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Paradise Club',
            'ad_type' => 'klub',
            'nationality' => 'slovenska',
            'age' => 30,
            'city' => 'zilina',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'viac-dievcat',
            'experience' => 'profesionalka',
            'phone' => '+421 907 555 444',
            'contact_methods' => ['telefon', 'whatsapp', 'email'],
            'practices' => ['privat', 'escort', 'skupinove', 'party'],
            'description' => 'Nový klub v centre Žiliny. Mladé krásne dievčatá, luxusné prostredie, party atmosféra.',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(14),
            'featured' => true,
            'phone_verified' => true,
            'views' => 1567,
            'clicks' => 123,
        ]);

        // Inzerát 16 - Trans v Bratislave
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Exotic Shemale',
            'ad_type' => 'trans',
            'nationality' => 'thajska',
            'age' => 23,
            'city' => 'bratislava',
            'street' => 'Ružinov',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'stredne-skusena',
            'phone' => '+421 908 222 777',
            'contact_methods' => ['telefon', 'whatsapp'],
            'practices' => ['escort', 'tantra', 'masaz', 'fetish'],
            'description' => 'Exotická krása z Thajska. Ponúkam úplne nové zážitky pre otvorených mužov.',
            'height' => 168,
            'weight' => 55,
            'breast_size' => '75C',
            'eye_color' => 'cierne',
            'hair_color' => 'cierne',
            'tattoos' => 'ano',
            'piercing' => 'ano',
            'orientation' => 'bisexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(16),
            'featured' => false,
            'phone_verified' => true,
            'views' => 934,
            'clicks' => 78,
        ]);

        // Inzerát 17 - Masáž v Nitre
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Healing Touch',
            'ad_type' => 'zena',
            'nationality' => 'ceska',
            'age' => 34,
            'city' => 'nitra',
            'offer_type' => 'masaz',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'profesionalka',
            'phone' => '+421 909 888 555',
            'contact_methods' => ['telefon', 'sms'],
            'practices' => ['masaz', 'relaxacna-masaz', 'reflexologia'],
            'description' => 'Certifikovaná masérka s dlhoročnými skúsenosťami. Ponúkam rôzne druhy masáží.',
            'height' => 162,
            'weight' => 57,
            'breast_size' => '75B',
            'eye_color' => 'hnede',
            'hair_color' => 'hnede',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => true,
            'views' => 345,
            'clicks' => 21,
        ]);

        // Inzerát 18 - Pár v Košiciach
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Wild Couple KE',
            'ad_type' => 'par',
            'nationality' => 'slovenska',
            'age' => 26,
            'city' => 'kosice',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'viac-dievcat',
            'experience' => 'stredne-skusena',
            'phone' => '+421 904 777 999',
            'contact_methods' => ['telefon', 'whatsapp'],
            'practices' => ['skupinove', 'swinging', 'fetish'],
            'description' => 'Divoký pár z východu. Milujeme experimenty a nové zážitky. Privátny byt k dispozícii.',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(11),
            'featured' => false,
            'phone_verified' => true,
            'views' => 678,
            'clicks' => 45,
        ]);

        // Inzerát 19 - Escort v Banskej Bystrici
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Classy Sarah',
            'ad_type' => 'zena',
            'nationality' => 'francuzska',
            'age' => 29,
            'city' => 'banska-bystrica',
            'offer_type' => 'stretnutie-u-teba',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'velmi-skusena',
            'phone' => '+421 901 444 333',
            'contact_methods' => ['telefon', 'whatsapp', 'email'],
            'practices' => ['escort', 'biznis-stretnutia', 'spolocenske-akcie'],
            'description' => 'Francúzska elegangia v srdci Slovenska. Vzdelaná, kultúrna, ideálna pre biznis stretnutia.',
            'height' => 173,
            'weight' => 59,
            'breast_size' => '80C',
            'eye_color' => 'modre',
            'hair_color' => 'hnede',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'active',
            'subscription_expires_at' => now()->addDays(27),
            'featured' => true,
            'phone_verified' => true,
            'views' => 1234,
            'clicks' => 89,
        ]);

        // Inzerát 20 - Študentka v Trnave
        Ad::create([
            'user_id' => $user->id,
            'nickname' => 'Student Girl',
            'ad_type' => 'zena',
            'nationality' => 'slovenska',
            'age' => 20,
            'city' => 'trnava',
            'offer_type' => 'stretnutie-u-mna',
            'girl_selection' => 'som-uplne-sama',
            'experience' => 'neskusena-zaciatocnicka',
            'phone' => '+421 903 666 111',
            'contact_methods' => ['telefon', 'sms'],
            'practices' => ['klasicky-sex', 'oralne'],
            'description' => 'Študentka univerzity potrebuje peniaze na školu. Som milá, čistá a diskrétna.',
            'height' => 166,
            'weight' => 50,
            'breast_size' => '70A',
            'eye_color' => 'modre',
            'hair_color' => 'blond',
            'tattoos' => 'nie',
            'piercing' => 'nie',
            'orientation' => 'heterosexualna',
            'status' => 'active',
            'subscription_status' => 'inactive',
            'featured' => false,
            'phone_verified' => false,
            'views' => 123,
            'clicks' => 12,
        ]);

        echo "Vytvorených 20 testovacích inzerátov!\n";
    }
}
